### Login
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "password"
}

### Obtener todos los usuarios
GET http://localhost:3003/api/users

### Crear un nuevo usuario
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "mluukkai",
    "name": "Matti Luukkainen",
    "password": "password"
}

### Obtener todos los blogs
GET http://localhost:3003/api/blogs

### Crear un nuevo elemento en la lista
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NTdjZGIzYWE0MTgzODBmNGI0ZTFjNmYiLCJpYXQiOjE3MDI5Mzc0MjQsImV4cCI6MTcwMjk0MTAyNH0.Dvn7Wvv3QWTqKNt95AG7OUd63OZ4-rBCWuqRJUHnHtU

{
    "title": "Blog 2",
    "author": "Miguel Angel",
    "url": "http://www.nuevoblog.com",
    "likes": 10
}

### Update a blog
PUT http://localhost:3003/api/blogs/6578bfffddf54ae4d
Content-Type: application/json

{
    "likes": 10
}

### Delete a blog
DELETE http://localhost:3003/api/blogs/657cdc711e5b238c46a8db7f